# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Documentation
author: https://github.com/mikeAdamss

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 120

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/mikeAdamss/tidychef # Online location of your book

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  confoverrides:
    python:
      sys.path: ['./venv/bin/python']
  extensions:
    - sphinx.ext.napoleon

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib
