name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main
    paths:
    - jupyterbook/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Create teh book via a venv
      run: |
        	rm -rf ./jupyterbook/_build
          rm -rf ./jupyterbook/venv
          python -m venv ./jupyterbook/venv
          . ./jupyterbook/venv/bin/activate
          pip install .
          jupyter-book build jupyterbook/ --all

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./jupyterbook/_build/html
