name: docs

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
    # Alternative: only build for tags.
    # tags:
    #   - '*'

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      # Create the docs, adding our own splash page and dynamically add
      # links to whatever scenarios we currently have.
      - run: pip install poetry
      - run: poetry install

      # We want to unzip the test scenarios as we're adding their expected html
      # outputs to the technical documentation. 
      - name: Unbundle test resources
        run: poetry run python3 resources/bundler.py unbundle
        
      - run: rm -rf ./docs
      - run: poetry run python3 ./expand_docs.py
      - run: poetry run pdoc -html ./datachef --output-dir ./docs
      - run: cp -a ./scenarios/html_scenario_fixtures/ ./docs/
      - run: cp ./_docs/splashpage.md ./docs/splashpage.md

      - run: tar --directory docs/ -hcf artifact.tar .
      - uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./artifact.tar
  
  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
